name: SBE_180391
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.10
  - samtools=1.18
  - racon=1.4.10
  - minimap2=2.17
  - snakemake=7.32.4
  - matplotlib
  - pysam=0.22.1
  - pandas=2.3.1
  - pyfastaq=3.18.0